import type { SkillCard } from "./types";

export const ALL_SKILL_CARDS: SkillCard[] = [
    // COMMON (5)
    {
        name: "Basic Training",
        description: "Increases all unit damage by a small amount",
        rarity: "COMMON",
        modifier: {
            type: "ALL_UNITS",
            target: "ALL",
            stat: "damage",
            isPercent: true,
            amount: 5,
            levelBonus: 2,
        },
    },
    {
        name: "Swift March",
        description: "Slightly increases movement speed for all units",
        rarity: "COMMON",
        modifier: {
            type: "ALL_UNITS",
            target: "ALL",
            stat: "speed",
            isPercent: true,
            amount: 8,
            levelBonus: 3,
        },
    },
    {
        name: "Elixir Boost",
        description: "Gain a small amount of bonus elixir",
        rarity: "COMMON",
        modifier: {
            type: "ECONOMIC",
            target: "Player",
            stat: "elixir",
            isPercent: true,
            amount: 10,
            levelBonus: 5,
        },
    },
    {
        name: "Reinforced Walls",
        description: "Increases castle HP slightly",
        rarity: "COMMON",
        modifier: {
            type: "DEFENSE",
            target: "Castle",
            stat: "hp",
            isPercent: true,
            amount: 8,
            levelBonus: 4,
        },
    },
    {
        name: "Skeleton Horde",
        description: "Reduces soldier cost slightly",
        rarity: "COMMON",
        modifier: {
            type: "SPECIFIC_UNIT",
            target: "soldier",
            stat: "cost",
            isPercent: true,
            amount: -10,
            levelBonus: -3,
        },
    },
    // FINE (4)
    {
        name: "Archer's Focus",
        description: "Increases archer damage moderately",
        rarity: "FINE",
        modifier: {
            type: "SPECIFIC_UNIT",
            target: "archer",
            stat: "damage",
            isPercent: true,
            amount: 15,
            levelBonus: 5,
        },
    },
    {
        name: "Battle Rhythm",
        description: "Increases attack speed for all units",
        rarity: "FINE",
        modifier: {
            type: "ALL_UNITS",
            target: "ALL",
            stat: "attacksPerMinute",
            isPercent: true,
            amount: 12,
            levelBonus: 4,
        },
    },
    {
        name: "Gold Rush",
        description: "Increases gold generation",
        rarity: "FINE",
        modifier: {
            type: "ECONOMIC",
            target: "Player",
            stat: "gold",
            isPercent: true,
            amount: 20,
            levelBonus: 8,
        },
    },
    {
        name: "Swordsman Mastery",
        description: "Increases swordsman HP and damage",
        rarity: "FINE",
        modifier: {
            type: "SPECIFIC_UNIT",
            target: "swordsman",
            stat: "hp",
            isPercent: true,
            amount: 18,
            levelBonus: 6,
        },
    },
    // RARE (4)
    {
        name: "Orcish Fury",
        description: "Significantly increases orc damage",
        rarity: "RARE",
        modifier: {
            type: "SPECIFIC_UNIT",
            target: "orc",
            stat: "damage",
            isPercent: true,
            amount: 25,
            levelBonus: 8,
        },
    },
    {
        name: "Eagle Eye",
        description: "Greatly increases attack range for all units",
        rarity: "RARE",
        modifier: {
            type: "ALL_UNITS",
            target: "ALL",
            stat: "attackRange",
            isPercent: true,
            amount: 20,
            levelBonus: 7,
        },
    },
    {
        name: "Castle Spikes",
        description: "Significantly increases castle counter damage",
        rarity: "RARE",
        modifier: {
            type: "DEFENSE",
            target: "Castle",
            stat: "counterDamage",
            isPercent: true,
            amount: 30,
            levelBonus: 10,
        },
    },
    {
        name: "Veteran Soldiers",
        description: "Greatly increases soldier HP",
        rarity: "RARE",
        modifier: {
            type: "SPECIFIC_UNIT",
            target: "soldier",
            stat: "hp",
            isPercent: true,
            amount: 28,
            levelBonus: 9,
        },
    },
    // EPIC (3)
    {
        name: "Warlord's Might",
        description: "Massively increases all unit damage",
        rarity: "EPIC",
        modifier: {
            type: "ALL_UNITS",
            target: "ALL",
            stat: "damage",
            isPercent: true,
            amount: 35,
            levelBonus: 12,
        },
    },
    {
        name: "Skeleton Archer Elite",
        description: "Skeleton archers gain massive attack speed",
        rarity: "EPIC",
        modifier: {
            type: "SPECIFIC_UNIT",
            target: "skeleton-archer",
            stat: "attacksPerMinute",
            isPercent: true,
            amount: 40,
            levelBonus: 15,
        },
    },
    {
        name: "Fortress",
        description: "Massively increases castle HP",
        rarity: "EPIC",
        modifier: {
            type: "DEFENSE",
            target: "Castle",
            stat: "hp",
            isPercent: true,
            amount: 45,
            levelBonus: 15,
        },
    },
    // LEGENDARY (2)
    {
        name: "Divine Blessing",
        description: "All units gain incredible HP",
        rarity: "LEGENDARY",
        modifier: {
            type: "ALL_UNITS",
            target: "ALL",
            stat: "hp",
            isPercent: true,
            amount: 50,
            levelBonus: 20,
        },
    },
    {
        name: "Gem Magnate",
        description: "Dramatically increases gem generation",
        rarity: "LEGENDARY",
        modifier: {
            type: "ECONOMIC",
            target: "Player",
            stat: "gems",
            isPercent: true,
            amount: 100,
            levelBonus: 25,
        },
    },
];
